apiVersion: v1
kind: Secret
metadata:
  name: banking-db-secrets
type: Opaque
stringData:
  postgres-password: "admin"
  account-db-url: "postgresql://postgres:admin@banking-postgres:5432/banking_account"
